# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87e9f731c9f51616185ffbf3f429af8dd42a872990a55f6d8a086e4f1dc846f0b551bbf63444f6e0293d0bdd5f4b4d18fa8c5f654ae3d76d4d28d088919ed087

test:
  secret_key_base: 8771a8bd8092d623a303174f810e4a1e6209216a5d715a83bdf95f904ef245976c15cdd98f229a339cd51144f9714f74ad78a1a53d203085a1a112f48f0b61c5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
